export type IconNames =
    | 'bitcoin'
    | 'bitcoin-medium'
    | 'arrows-cyrcle'
    | 'ton'
    | 'burger'
    | 'plus'
    | 'flag'
    | 'arrow-up'
    | 'arrow-down'
    | 'arrow-right'
    | 'persons'
    | 'wallet'
    | 'arrow-refund'
    | 'cross'
    | 'handshake'
    | 'support'
    | 'x-twitter'
    | 'telegram'
    | 'facebook'
    | 'instagram'
    | 'tether'
    | 'notcoin'

    export type IconType =
    | 'small'
    | 'medium'
    | 'big'