export type IconNames =
    | 'bitcoin'
    | 'arrows-cyrcle'
    | 'ton'
    | 'burger'
    | 'plus'
    | 'flag'
    | 'arrow-up'
    | 'arrow-down'
    | 'arrow-right'
    | 'persons'
    | 'wallet'
    | 'arrow-refund'
    | 'cross'
    | 'handshake'
    | 'support'
    | 'x-twitter'
    | 'telegram'
    | 'facebook'
    | 'instagram'
    | 'tether'
    | 'notcoin'
    | 'copy'
    | 'etherium-coin'
    | 'gold-coin'
    | 'oil-coin'
    | 'solana-coin'
    | 'nasdaq-coin'
    | 'sp500-coin'

    export type IconType =
    | 'small'
    | 'medium'
    | 'big'