export { userDataWalletReducer, userDataTelegramReducer } from './user'
export { betsReducer } from './bets'
export { gameStatusReducer } from './game'
export { langReducer } from './language'
export { modeReducer } from './mode'
export { socketReducer } from './socket'
